server:
  port: 8888
  servlet:
    context-path: /hrm

spring:
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      additional-exclude: WEB-INF/**
